### PR TITLE
Use var_export to output value without locale formatting

### PR DESCRIPTION
**Pull request by monptitjojo**
Use var_export to output value without locale formatting

For example calling `setLocale(LC_ALL, 'fr-FR’);` before send timing will send value with « , » instead of « . » to statsd

### CODE REVIEW

**Comment by marcqualie** [comment]
@monptitjojo Is it possible to achieve this via some kind of optional wrapper rather than add the function call overhead to every request? Most applications won't need this and statsd by design should be as minimal a footprint in an application as possible.

**Comment by staabm** [comment]
Why do the lines you change here depend on the `locale`? its just a echo which doesn't work differently per local? only thing I can think of is that you `echo` a object which in turn uses `__toString()` and some locale-related formating function inside it...?

**Comment by monptitjojo** [comment]
@staabm PHP when it converts to string apply locale setting

For example, this code emulate what timing fonction actually do

**Comment by marcqualie** [comment]
@monptitjojo I understand the reasoning behind it, I'm just reluctant to add this to the core library as it's specific to your application data input. I would recommend wrapping the calls to statsd as follows:

```
$statsd->gauge('metric', var_export($value));
```

This would avoid adding the function call for every other user of this library where it's not required.

**Comment by monptitjojo** [comment]
It is not specific to my data input, I use startTiming / endTiming et time méthod... The data are computed by the library.

**Pull request closed without merging**
